# Generated by Django 2.0.1 on 2018-02-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20180207_2244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_ratedlist_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'So Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'High'), (5, 'So High')], default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
