# Generated by Django 2.0.1 on 2018-02-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180209_1601'),
        ('users', '0009_categorylist'),
    ]

    operations = [
    ]
