# Generated by Django 2.0.2 on 2018-02-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
