<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-02-06 13:52
=======
# Generated by Django 2.0.1 on 2018-02-06 22:31
>>>>>>> bc19e79b24a468f3d6a25e6d09261a8795916412

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
