# Generated by Django 2.0.2 on 2018-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20180205_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='born_at',
            field=models.DateField(default='0000-00-0', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='authors',
            name='died_at',
            field=models.DateField(default='0000-00-0', verbose_name='Date'),
        ),
    ]
