# Generated by Django 2.0.2 on 2018-02-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20180205_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='died_at',
        ),
        migrations.AlterField(
            model_name='authors',
            name='born_at',
            field=models.DateField(default='2010-01-01', verbose_name='Date'),
        ),
    ]
