# Generated by Django 2.0.2 on 2018-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20180205_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='died_at',
            field=models.DateField(default='2010-01-01', verbose_name='Date'),
        ),
    ]
