# Generated by Django 2.0.2 on 2018-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_authors_died_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='died_at',
            field=models.DateField(default='2010-01-01'),
        ),
    ]
