# Generated by Django 2.0.2 on 2018-02-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_auto_20180205_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='died_at',
            field=models.DateField(),
        ),
    ]
