# Generated by Django 2.0.2 on 2018-02-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_auto_20180205_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_nationality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authors',
            name='bio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='authors',
            name='contacts',
            field=models.CharField(max_length=200),
        ),
    ]
