# Generated by Django 2.0.2 on 2018-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_auto_20180205_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='died_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
