# Generated by Django 2.0.2 on 2018-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_auto_20180205_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='died_at',
            field=models.DateField(null=True),
        ),
    ]
