# Generated by Django 2.0.2 on 2018-02-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_auto_20180205_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='born_at',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='died_at',
        ),
    ]
