# Generated by Django 2.0.1 on 2018-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(choices=[(1, 'So Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'High'), (5, 'So High')], default=3),
        ),
    ]
