# Generated by Django 2.0.1 on 2018-02-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
