# Generated by Django 2.0.1 on 2018-02-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
