# Generated by Django 2.0.1 on 2018-02-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180207_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
