# Generated by Django 2.0.1 on 2018-02-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_readedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readedlist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readedlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadedList',
        ),
    ]
